### ISSUE TITLE
v2 seems te be wrongly tagged

### ISSUE THREAD

**Issue by rubenvanerk** [JustSteveKing/php-sdk#11]
It was tagged on https://github.com/JustSteveKing/php-sdk/commit/64c6bbabf800a2250aa992722d4406ae7d5d2059, a commit from Jun 3, 2021. The commits that seem to be related to v2 are all committed on Jan 21, 2022.

**Comment by JustSteveKing** [comment]
I think this is because I did a lot of the work for v2 in january and didn't get back to it until June 😆
